<?php


namespace SwooleSidecarTest;

use PHPUnit\Framework\TestCase;
use SwooleSidecar\ApolloClient\ApolloClient;

class ApolloTest extends TestCase
{
    private $client = null;
    /**
     * set up
    */
    public function setUp():void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = ApolloClient::once();

    }

    public function tearDown():void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->client = null;
    }

    public function testApolloPullWithoutCache(){
        $namespace = "application";
        $data = $this->client->pullWithOutCache($namespace);
        $this->assertEquals(200,$data->getCode());
    }

    public function testApolloPullWithCache(){
        $namespace = "application";
        $data = $this->client->pullWithOutCache($namespace);
        $this->assertEquals(200,$data->getCode());
    }

}