<?php


namespace SwooleSidecarTest;


use PHPUnit\Framework\TestCase;
use SwooleSidecar\EurekaClient\EurekaClient;

class EurekaTest extends TestCase
{
    private $client = null;
    public function setUp():void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = EurekaClient::once();
    }

    public function tearDown():void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->client = null;
    }

    public function testHealth(){
        $status = $this->client->health();
        $this->assertEquals(true,$status);
    }

    public function testInstance(){
        $appid = 'test-v1';
        $res = $this->client->instance($appid);
        $this->assertNotEmpty($res);
    }
}